name: Concurrency 1
run-name: Concurrency 1 ${{ inputs.environment }}
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        type: environment
        required: true

concurrency: 
  group: ${{ inputs.environment }} # concurrency group
  cancel-in-progress: true # starts the latest run and cancels other runs
jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30