name: Docker
on: [workflow_dispatch]

jobs:
  docker-job:
    runs-on: ubuntu-latest
    container: 
      image: node:21-alpine3.18
      # credentials:
      #   username: 
      #   password: 
      env:
        API_URL: some-url.com
      ports:
        - 80
      # volumes:
      #   - vol_name:/path/in/container # named volume
      #   - /path/to/container # anonymous volume
      #   - /path/in/host:/path/in/container # bind mount
      # options: --cpus 1
    steps:
      - name: Log Node & OS Versions
        run: |
          node -v
          cat /etc/os-release
      - name: Log Env
        run: echo $API_URL
      - name: Create a file
        run: echo 'Some text' > text.txt 
      - name: Container in a Step
        uses: docker://node:18.16-alpine3.17
        with:
          entrypoint: /usr/local/bin/node # not needed because node already runs by default
          args: -p 2+3 # used in place of the command instruction in a dockerfile
      - name: Log node version
        uses: docker://node:18.16-alpine3.17
        with:
          args: -v # node -v
      - name: Show file contents
        uses: docker://node:18.16-alpine3.17
        with:
          entrypoint: cat
          args: text.txt
      - uses: actions/checkout@v3
      - name: Run a bash script
        uses: docker://node:18.16-alpine3.17
        with:
          entrypoint: ./script.sh
          args: "Some string"
          
      # the following steps are used to post a notification to slack
      # - name: Send a slack message
      #   uses: docker://technosophos/slack-notify
        # env:
        #   SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        #   SLACK_TITLE: From Github Actions
        #   SLACK_MESSAGE: "Actor: ${{github.actor}}, Event: ${{github.event_name}}"
        #   SLACK_COLOR: "#723fc4"
