name: Matrix
on: [push]

jobs:
  node-matrix: 
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [14,15,16] # executes 3 jobs, one for each version
    runs-on: ${{ matrix.os }}
    steps:
      - run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: node -v
