name: Matrix
on: [push]

#------- ORIGINAL --------#
# X {os: ubuntu-latest, node-version: 14, is-ubuntu: true, experimental: false}
# {os: ubuntu-latest, node-version: 15, is-ubuntu: true, experimental: false}
# {os: ubuntu-latest, node-version: 16, is-ubuntu: true, experimental: true}
# {os: windows-latest, node-version: 14, experimental: false}
# {os: windows-latest, node-version: 15, experimental: false}
# {os: windows-latest, node-version: 16, experimental: false}
# {os: macos-latest, node-version: 15}
# {os: ubuntu-latest, node-version: 17 }

jobs:
  node-matrix: 
    continue-on-error: ${{ matrix.experimental == true }} # overrides fail-fast and does not stop entire workflow when a job fails
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [14,15,16] # executes 3 jobs, one for each version
        include:
          - os: ubuntu-latest
            is-ubuntu: true
          - os: macos-latest
            node-version: 15
          - experimental: false
          - os: ubuntu-latest
            node-version: 16
            experimental: true
          - os: ubuntu-latest
            node-version: 17
        exclude:
          - os: ubuntu-latest
            node-version: 14
      fail-fast: true
      # max-parallel:
    runs-on: ${{ matrix.os }} # runs on 2 OSs
    steps:
      - if: matrix.experimental == true
        run: exit 1
      - run: node -v
      - run: echo '${{ toJson(matrix) }}'
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: node -v
