name: Calling Reusable Workflows
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Input description'
        type: string
        default: 'Pedro'
        required: false

jobs:
  calling-a-reusable-wf:
    uses: github-actions-udemy/workflows/.github/workflows/reusable.yaml@main # calls another workflow
    with:
      name: ${{ inputs.name }}
    secrets:
      access-token: ${{ secrets.ACCESS_TOKEN }}
  calling-a-reusable-wf-in-the-same-repo:
    uses: ./.github/workflows/reusable-workflow.yaml
    secrets: inherit # passes all secrets from the caller workflow to this wf
  using-reusable-workflow-output:
    runs-on: ubuntu-latest
    needs: calling-a-reusable-wf-in-the-same-repo
    steps:
      - run: echo ${{ needs.calling-a-reusable-wf-in-the-same-repo.outputs.date }}
